# Generated by Django 3.2.18 on 2023-05-24 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_userfavoritemovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavoritemovie',
            name='user',
        ),
        migrations.AddField(
            model_name='userfavoritemovie',
            name='user',
            field=models.ManyToManyField(related_name='like_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
