# Generated by Django 3.2.18 on 2023-05-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_author_comment_user'),
        ('movies', '0004_auto_20230524_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='comment_movies', to='comments.Comment'),
        ),
    ]
