# Generated by Django 3.2.18 on 2023-05-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='comment',
        ),
    ]
